[package]
name = "kokia-target"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nix.workspace = true
anyhow.workspace = true
thiserror.workspace = true
kokia-dwarf = { path = "../kokia-dwarf" }

[dev-dependencies]
